# permissions for end users to view cordas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: corda-viewer-role
rules:
- apiGroups:
  - corda.kubecorda.com
  resources:
  - cordas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - corda.kubecorda.com
  resources:
  - cordas/status
  verbs:
  - get
